Aim : Write a program to implement Delta Rule.

In [1]:
import numpy as np

In [2]:
x=np.zeros((3,))

In [3]:
weights=np.zeros((3,))

In [4]:
desired=np.zeros((3,))

In [5]:
actual=np.zeros((3,))

In [6]:
for i in range(0,3):
    x[i]=float(input("Initial Inputs:"))

Initial Inputs:1
Initial Inputs:1
Initial Inputs:1


In [7]:
for i in range(0,3):
    weights[i]=float(input("Initial Weights:"))

Initial Weights:1
Initial Weights:1
Initial Weights:1


In [8]:
for i in range(0,3):
    desired[i]=float(input("Desired Inputs:"))

Desired Inputs:2
Desired Inputs:3
Desired Inputs:4


In [10]:
a=float(input("Enter learning rate"))

Enter learning rate1


In [11]:
x

array([1., 1., 1.])

In [12]:
weights

array([1., 1., 1.])

In [13]:
desired

array([2., 3., 4.])

In [14]:
actual=x*weights

In [15]:
print("Actual output",actual)
print("Desired output",desired)

Actual output [1. 1. 1.]
Desired output [2. 3. 4.]


In [16]:
while True:
    if np.array_equal(desired,actual):
        break
    else:
        for i in range(0,3):
            weights[i]=weights[i]+a*(desired[i]-actual[i])
            actual=x*weights

In [17]:
print("Final Output")
print("Corrected Weights",weights)
print("Actual Output",actual)
print("Desired Output",desired)

Final Output
Corrected Weights [2. 3. 4.]
Actual Output [2. 3. 4.]
Desired Output [2. 3. 4.]
